# .gitlab-ci.yml
image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
    - mv dist public  # GitLab Pages butuh folder bernama public
  artifacts:
    paths:
      - public
  only:
    - main  # atau ganti ke nama branch kamu
